name: Build OpenWrt TL-WR840N v6.2 (19.07)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-wr840n-v62.yml'
      - '.config'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python


      - name: Show CPU/mem
        run: |
          nproc
          free -h
          uname -a

      - name: Prepare .config
        run: |
          cat > .config <<'EOF'
          # ===== TARGET DEVICE =====
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt76x8=y
          CONFIG_TARGET_ramips_mt76x8_DEVICE_tplink_tl-wr840n-v6=y
          
          # ===== DRIVER & CORE SYSTEM =====
          CONFIG_PACKAGE_kmod-mt76x8=y
          CONFIG_PACKAGE_wpad-basic-wolfssl=y
          
          # ===== LUCI (Web UI) =====
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_luci-mod-status=y
          CONFIG_PACKAGE_luci-app-firewall=y
          
          # ===== SQM QoS =====
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_sqm-scripts=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_tc=y
          CONFIG_PACKAGE_ip-full=y
          
          # ===== SIZE OPTIMIZATION (WAJIB UNTUK 4MB) =====
          CONFIG_IPV6=n
          CONFIG_PACKAGE_ipv6helper=n
          CONFIG_PACKAGE_ppp=n
          CONFIG_PACKAGE_pppoe=n
          CONFIG_PACKAGE_kmod-ppp=n
          CONFIG_PACKAGE_kmod-pppoe=n
          CONFIG_PACKAGE_kmod-ipv6=n
          CONFIG_PACKAGE_luci-proto-ppp=n
          CONFIG_PACKAGE_luci-ssl=n
          CONFIG_PACKAGE_opkg=n
          CONFIG_BUSYBOX_CUSTOM=n
          
          # ===== LOGGING (optional untuk debug GitHub Actions) =====
          CONFIG_BUILD_LOG=y
          EOF

      - name: Feeds update/install
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Make defconfig (normalize)
        run: |
          make defconfig
          echo "== Final diffconfig =="
          ./scripts/diffconfig.sh || true

      - name: Build
        env:
          FORCE_UNSAFE_CONFIGURE: "1"
        run: |
          make -j$(nproc) V=s

      - name: Collect artifacts
        if: ${{ always() }}
        run: |
          mkdir -p artifact
          find bin/targets -type f -maxdepth 4 -print0 | xargs -0 -I{} cp "{}" artifact/ || true
          ls -lh artifact || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-wr840n-v6.2-19.07
          path: artifact/*
          if-no-files-found: warn
          retention-days: 14
